### ISSUE TITLE
Licensing compliance

### ISSUE THREAD

**Issue by fabrizioschiavi** [ootput/dotfiles#1]
PragmataPro is not free software and I ,the author, haven't ever made it available in a particularly permissive form. Also worth noting - you appear to have an older (buggy) version of PragmataPro which is missing certain ligatures added in 0.820.
http://www.fsd.it/fonts/pragmatapro.htm
http://www.fsd.it/fonts/eula.htm

**Comment by ootput** [comment]
Oh, sorry about that.

I found the font on another users dotfiles repo - though I don't remember who.
I'll take off the offending file immediately.

Thanks for the notice

**Comment by fabrizioschiavi** [comment]
Thanks for your undestanding! 
All the best
